### PR TITLE
Added a website template for listing packages

### PR DESCRIPTION
**Pull request by orels1**
This adds a Scriban-templated webpage and app.js script to list packages from the provided listing

[Flows Miro Board](https://miro.com/app/board/uXjVP-3KHbI=/?share_link_id=759955484684)

Previews:
image (7)
image (8)

### CODE REVIEW

**Review by momo-the-monster — APPROVED** [review]
Looks great! Can you take screenshots of all the possible states (including info bubbles or modals) and post them to a Miro for the feedback on layout and info?

**Comment by orels1** [comment]
@momo-the-monster updated the description with the Miro link

**Comment by Faxmashine** [comment]
A community member recently requested
> Will the new UI show the source repo for each package in the listing so you can see at a glance where each individual package is from to verify it's the desired one?

Seems like a good idea to include that information somewhere.

**Comment by momo-the-monster** [comment]
> Will the new UI show the source repo for each package in the listing so you can see at a glance where each individual package is from to verify it's the desired one?

Captured in [a BC to-do](https://3.basecamp.com/3952707/buckets/18273675/todos/5595988759).

**Pull request merged**
